# Generated by Django 4.2.5 on 2023-11-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pic')),
                ('dis', models.TextField()),
            ],
        ),
    ]
